//
//  Milestone.swift
//  DevCal
//

import Foundation
import SwiftData

@Model
final class Milestone {
    var id: UUID = UUID()
    var typeRaw: String = MilestoneType.manual.rawValue
    var title: String = ""
    var note: String = ""
    var date: Date = Date()
    var autoGenerated: Bool = false
    var createdAt: Date = Date()

    var project: Project?

    init(
        type: MilestoneType = .manual,
        title: String = "",
        note: String = "",
        date: Date = Date(),
        autoGenerated: Bool = false,
        project: Project? = nil
    ) {
        self.id = UUID()
        self.typeRaw = type.rawValue
        self.title = title
        self.note = note
        self.date = date
        self.autoGenerated = autoGenerated
        self.project = project
        self.createdAt = Date()
    }

    var type: MilestoneType {
        get { MilestoneType(rawValue: typeRaw) ?? .manual }
        set { typeRaw = newValue.rawValue }
    }
}
