//
//  MilestoneDocument.swift
//  DevCal
//
//  Remote / sync representation of a Milestone. See ProjectDocument for
//  shared conventions.
//

import Foundation

struct MilestoneDocument: Codable, Equatable, Sendable {
    var id: String
    var projectId: String?
    var typeRaw: String
    var title: String
    var note: String
    var date: Date
    var autoGenerated: Bool
    var createdAt: Date
    var updatedAt: Date
    var isDeleted: Bool
}

extension MilestoneDocument {
    init(from milestone: Milestone) {
        self.id = milestone.id.uuidString
        self.projectId = milestone.project?.id.uuidString
        self.typeRaw = milestone.typeRaw
        self.title = milestone.title
        self.note = milestone.note
        self.date = milestone.date
        self.autoGenerated = milestone.autoGenerated
        self.createdAt = milestone.createdAt
        // Milestone has no updatedAt in SwiftData yet — mirror createdAt so the
        // sync layer has a stable last-write-wins anchor. When Phase 1 lands,
        // upgrade Milestone with a real `updatedAt`.
        self.updatedAt = milestone.createdAt
        self.isDeleted = false
    }

    func apply(to milestone: Milestone) {
        milestone.typeRaw = typeRaw
        milestone.title = title
        milestone.note = note
        milestone.date = date
        milestone.autoGenerated = autoGenerated
        milestone.createdAt = createdAt
    }

    func makeMilestone() -> Milestone {
        let milestone = Milestone()
        milestone.id = UUID(uuidString: id) ?? UUID()
        apply(to: milestone)
        return milestone
    }
}
