//
//  MilestoneRepository.swift
//  DevCal
//
//  Write boundary for manually-added Milestone records. Auto-detected
//  milestones (`firstIncome`, `breakEven25/50/75`, …) are derived from
//  current transaction data and are not persisted, so they don't pass
//  through here. The repository covers user-created `Milestone(type: .manual)`
//  rows: create on tap of `AddManualMilestoneView` save, delete on swipe.
//

import Foundation
import SwiftData

@MainActor
final class MilestoneRepository {
    private let context: ModelContext
    private let sync: SyncServicing

    init(context: ModelContext, sync: SyncServicing) {
        self.context = context
        self.sync = sync
    }

    @discardableResult
    func createManualMilestone(
        project: Project,
        title: String,
        note: String,
        date: Date
    ) async throws -> Milestone {
        let trimmed = title.trimmingCharacters(in: .whitespaces)
        guard !trimmed.isEmpty else {
            throw DataLayerError.invalidInput("Milestone title cannot be empty.")
        }
        let milestone = Milestone(
            type: .manual,
            title: trimmed,
            note: note,
            date: date,
            autoGenerated: false,
            project: project
        )
        context.insert(milestone)
        try save()
        try enqueueSync(for: milestone)
        return milestone
    }

    func deleteMilestone(_ milestone: Milestone) async throws {
        let document = MilestoneDocument(from: milestone).tombstoned
        context.delete(milestone)
        try save()
        try enqueueTombstone(document)
    }

    // MARK: - Internals

    private func save() throws {
        do {
            try context.save()
        } catch {
            throw DataLayerError.localSaveFailed(underlying: error)
        }
    }

    private func enqueueSync(for milestone: Milestone) throws {
        let doc = MilestoneDocument(from: milestone)
        let op = try PendingSyncOperation.make(
            entityId: doc.id,
            kind: .milestone,
            document: doc
        )
        sync.enqueue(op)
    }

    private func enqueueTombstone(_ document: MilestoneDocument) throws {
        let op = try PendingSyncOperation.make(
            entityId: document.id,
            kind: .milestone,
            document: document
        )
        sync.enqueue(op)
    }
}

private extension MilestoneDocument {
    var tombstoned: MilestoneDocument {
        var copy = self
        copy.isDeleted = true
        copy.updatedAt = Date()
        return copy
    }
}
