//
//  FirestoreSyncPullMilestoneTests.swift
//  DevCalTests
//
//  Step 4 pull coverage for `Milestone` — closes Phase 4 pull. Milestone
//  has no `updatedAt` field on the SwiftData model yet (the DTO mirrors
//  createdAt on write), so the LWW anchor on pull is `doc.updatedAt`
//  vs `existing.createdAt`. The DTO's apply() does not mutate
//  Milestone.createdAt, so a re-pull is idempotent.
//

import Testing
import Foundation
import SwiftData
@testable import DevCal

@MainActor
struct FirestoreSyncPullMilestoneTests {

    private func makeContext() throws -> ModelContext {
        let schema = Schema([
            Project.self,
            Transaction.self,
            TimeLog.self,
            Milestone.self,
            CategoryItem.self
        ])
        let config = ModelConfiguration(schema: schema, isStoredInMemoryOnly: true)
        let container = try ModelContainer(for: schema, configurations: [config])
        return container.mainContext
    }

    private func makeTempQueueURL() -> URL {
        let dir = URL.temporaryDirectory.appendingPathComponent(
            "FirestoreSyncPullMilestoneTests-\(UUID().uuidString)",
            isDirectory: true
        )
        try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        return dir.appendingPathComponent("sync-queue.json", isDirectory: false)
    }

    private func makeMilestoneDoc(
        id: UUID = UUID(),
        projectId: String? = nil,
        title: String = "回本",
        updatedAt: Date = Date(timeIntervalSince1970: 1_700_000_500),
        isDeleted: Bool = false
    ) -> MilestoneDocument {
        MilestoneDocument(
            id: id.uuidString,
            projectId: projectId,
            typeRaw: "breakeven",
            title: title,
            note: "",
            date: Date(timeIntervalSince1970: 1_700_000_000),
            autoGenerated: false,
            createdAt: updatedAt,
            updatedAt: updatedAt,
            isDeleted: isDeleted
        )
    }

    private func makeService(context: ModelContext, reader: MockRemoteReader) -> FirestoreSyncService {
        FirestoreSyncService(
            currentUID: { "uid-1" },
            queueURL: makeTempQueueURL(),
            remote: MockRemoteWriter(),
            reader: reader,
            modelContext: context
        )
    }

    @Test("upsertMilestone hydrates the parent project when it exists locally")
    func upsertHydratesProject() throws {
        let context = try makeContext()
        let service = makeService(context: context, reader: MockRemoteReader())

        let projectId = UUID()
        let project = Project(name: "Parent")
        project.id = projectId
        context.insert(project)
        try context.save()

        try service.upsertMilestone(
            makeMilestoneDoc(projectId: projectId.uuidString),
            context: context
        )
        try context.save()

        let all = try context.fetch(FetchDescriptor<Milestone>())
        #expect(all.first?.project?.id == projectId)
    }

    @Test("upsertMilestone LWW: newer remote replaces local (pivot on local.createdAt)")
    func upsertAppliesNewerRemote() throws {
        let context = try makeContext()
        let service = makeService(context: context, reader: MockRemoteReader())
        let id = UUID()

        let local = Milestone()
        local.id = id
        local.title = "舊里程碑"
        local.createdAt = Date(timeIntervalSince1970: 1_700_000_000)
        context.insert(local)
        try context.save()

        try service.upsertMilestone(
            makeMilestoneDoc(id: id, title: "新里程碑", updatedAt: Date(timeIntervalSince1970: 1_700_000_500)),
            context: context
        )
        try context.save()

        let all = try context.fetch(FetchDescriptor<Milestone>())
        #expect(all.first?.title == "新里程碑")
    }

    @Test("upsertMilestone LWW: older remote leaves local alone")
    func upsertKeepsNewerLocal() throws {
        let context = try makeContext()
        let service = makeService(context: context, reader: MockRemoteReader())
        let id = UUID()

        let local = Milestone()
        local.id = id
        local.title = "本機贏"
        local.createdAt = Date(timeIntervalSince1970: 1_700_000_500)
        context.insert(local)
        try context.save()

        try service.upsertMilestone(
            makeMilestoneDoc(id: id, title: "舊雲端", updatedAt: Date(timeIntervalSince1970: 1_700_000_000)),
            context: context
        )
        try context.save()

        let all = try context.fetch(FetchDescriptor<Milestone>())
        #expect(all.first?.title == "本機贏")
    }

    @Test("upsertMilestone deletes local row on tombstone")
    func upsertDeletesOnTombstone() throws {
        let context = try makeContext()
        let service = makeService(context: context, reader: MockRemoteReader())
        let id = UUID()

        let local = Milestone()
        local.id = id
        context.insert(local)
        try context.save()

        try service.upsertMilestone(makeMilestoneDoc(id: id, isDeleted: true), context: context)
        try context.save()

        let all = try context.fetch(FetchDescriptor<Milestone>())
        #expect(all.isEmpty)
    }

    @Test("syncNow pulls every entity kind in a single pass")
    func syncNowPullsAllFiveKinds() async throws {
        let context = try makeContext()
        let reader = MockRemoteReader()

        let projectId = UUID()
        var projectDoc = ProjectDocument(
            id: projectId.uuidString,
            name: "Cloud project",
            projectDescription: "",
            statusRaw: "live",
            kindRaw: "app",
            iconImageData: nil,
            iconPhName: nil,
            iconColorHex: nil,
            launchDate: nil,
            createdAt: Date(),
            updatedAt: Date(),
            archivedAt: nil,
            sortIndex: 0,
            breakevenReachedAt: nil,
            goalAmount: nil,
            goalCurrencyCode: nil,
            goalDeadline: nil,
            isDeleted: false
        )
        projectDoc.updatedAt = Date(timeIntervalSince1970: 1_700_000_500)

        reader.projects = [projectDoc]
        reader.transactions = [
            TransactionDocument(
                id: UUID().uuidString,
                projectId: projectId.uuidString,
                typeRaw: "expense",
                categoryRaw: "subscription",
                name: "Cursor",
                iconBrandKey: nil,
                iconFallbackName: nil,
                iconColorHex: nil,
                originalAmount: 199,
                originalCurrencyCode: "USD",
                note: "",
                date: Date(),
                createdAt: Date(),
                updatedAt: Date(timeIntervalSince1970: 1_700_000_500),
                sourceCategoryItemId: nil,
                deterministicId: nil,
                isDeleted: false
            )
        ]
        reader.timeLogs = [
            TimeLogDocument(
                id: UUID().uuidString,
                projectId: projectId.uuidString,
                hours: 4,
                hourlyRate: 1000,
                hourlyCurrencyCode: "TWD",
                note: "",
                date: Date(),
                createdAt: Date(),
                updatedAt: Date(timeIntervalSince1970: 1_700_000_500),
                isDeleted: false
            )
        ]
        reader.categoryItems = [
            CategoryItemDocument(
                id: UUID().uuidString,
                name: "AI tools",
                categoryRaw: "subscription",
                totalAmount: 600,
                originalCurrencyCode: "USD",
                billingTypeRaw: "monthly",
                brandIconKey: nil,
                fallbackIconName: nil,
                iconColorHex: nil,
                nextDueDate: nil,
                isActive: true,
                isShared: false,
                splitModeRaw: "equal",
                weightsByProjectId: nil,
                projectIds: [projectId.uuidString],
                createdAt: Date(),
                updatedAt: Date(timeIntervalSince1970: 1_700_000_500),
                isDeleted: false
            )
        ]
        reader.milestones = [makeMilestoneDoc(projectId: projectId.uuidString)]

        let service = makeService(context: context, reader: reader)
        try await service.syncNow()

        let projects = try context.fetch(FetchDescriptor<Project>())
        let txns = try context.fetch(FetchDescriptor<Transaction>())
        let logs = try context.fetch(FetchDescriptor<TimeLog>())
        let cats = try context.fetch(FetchDescriptor<CategoryItem>())
        let milestones = try context.fetch(FetchDescriptor<Milestone>())

        #expect(projects.count == 1)
        #expect(txns.count == 1)
        #expect(logs.count == 1)
        #expect(cats.count == 1)
        #expect(milestones.count == 1)
        #expect(txns.first?.project?.id == projectId)
        #expect(service.status == .idle)
    }
}
