//
//  FirestoreSyncPushMilestoneTests.swift
//  DevCalTests
//
//  Step 3 push coverage for the `Milestone` entity kind — closes the five
//  entity kinds. Milestone's `updatedAt` currently mirrors `createdAt` (the
//  SwiftData model has no real `updatedAt` yet, see MilestoneDocument.swift)
//  so the test asserts on the createdAt-derived stamp.
//

import Testing
import Foundation
@testable import DevCal

@MainActor
struct FirestoreSyncPushMilestoneTests {

    // MARK: - Helpers

    private func makeTempQueueURL() -> URL {
        let dir = URL.temporaryDirectory.appendingPathComponent(
            "FirestoreSyncPushMilestoneTests-\(UUID().uuidString)",
            isDirectory: true
        )
        try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        return dir.appendingPathComponent("sync-queue.json", isDirectory: false)
    }

    private func makeMilestoneDocument(
        id: UUID = UUID(),
        autoGenerated: Bool = false
    ) -> MilestoneDocument {
        MilestoneDocument(
            id: id.uuidString,
            projectId: UUID().uuidString,
            typeRaw: "breakeven",
            title: "回本里程碑",
            note: "first month above break-even",
            date: Date(timeIntervalSince1970: 1_700_000_000),
            autoGenerated: autoGenerated,
            createdAt: Date(timeIntervalSince1970: 1_700_000_000),
            updatedAt: Date(timeIntervalSince1970: 1_700_000_000),
            isDeleted: false
        )
    }

    private func makeOp(_ doc: MilestoneDocument) throws -> PendingSyncOperation {
        try PendingSyncOperation.make(entityId: doc.id, kind: .milestone, document: doc)
    }

    // MARK: - encodePush

    @Test("encodePush routes Milestone ops to the milestones collection")
    func encodePushRoutesMilestone() throws {
        let service = FirestoreSyncService(
            currentUID: { "uid-1" },
            queueURL: makeTempQueueURL(),
            remote: MockRemoteWriter()
        )
        let doc = makeMilestoneDocument(autoGenerated: true)
        let op = try makeOp(doc)

        let push = try service.encodePush(op, ownerUid: "uid-1")

        #expect(push?.collection == "milestones")
        #expect(push?.fields["title"] as? String == "回本里程碑")
        #expect(push?.fields["typeRaw"] as? String == "breakeven")
        #expect(push?.fields["autoGenerated"] as? Bool == true)
    }

    // MARK: - syncNow push pass

    @Test("syncNow pushes pending Milestone ops and acks them")
    func syncNowPushesMilestone() async throws {
        let remote = MockRemoteWriter()
        let service = FirestoreSyncService(
            currentUID: { "uid-5" },
            queueURL: makeTempQueueURL(),
            remote: remote
        )
        let doc = makeMilestoneDocument()
        service.enqueue(try makeOp(doc))

        try await service.syncNow()

        #expect(remote.calls == [.init(collection: "milestones", documentId: doc.id)])
        #expect(service.snapshotQueue().isEmpty)
    }

    // MARK: - All five kinds drain together

    @Test("syncNow drains all 5 entity kinds in a single pass")
    func syncNowDrainsAllFiveKinds() async throws {
        let remote = MockRemoteWriter()
        let service = FirestoreSyncService(
            currentUID: { "uid-1" },
            queueURL: makeTempQueueURL(),
            remote: remote
        )

        let projectDoc = ProjectDocument(
            id: UUID().uuidString,
            name: "P",
            projectDescription: "",
            statusRaw: "live",
            kindRaw: "app",
            iconImageData: nil,
            iconPhName: nil,
            iconColorHex: nil,
            launchDate: nil,
            createdAt: Date(),
            updatedAt: Date(),
            archivedAt: nil,
            sortIndex: 0,
            breakevenReachedAt: nil,
            goalAmount: nil,
            goalCurrencyCode: nil,
            goalDeadline: nil,
            isDeleted: false
        )
        let txnDoc = TransactionDocument(
            id: UUID().uuidString,
            projectId: projectDoc.id,
            typeRaw: "expense",
            categoryRaw: "subscription",
            name: "Cursor",
            iconBrandKey: nil,
            iconFallbackName: nil,
            iconColorHex: nil,
            originalAmount: 199,
            originalCurrencyCode: "USD",
            note: "",
            date: Date(),
            createdAt: Date(),
            updatedAt: Date(),
            sourceCategoryItemId: nil,
            deterministicId: nil,
            isDeleted: false
        )
        let logDoc = TimeLogDocument(
            id: UUID().uuidString,
            projectId: projectDoc.id,
            hours: 1,
            hourlyRate: 1000,
            hourlyCurrencyCode: "TWD",
            note: "",
            date: Date(),
            createdAt: Date(),
            updatedAt: Date(),
            isDeleted: false
        )
        let catDoc = CategoryItemDocument(
            id: UUID().uuidString,
            name: "AI tools",
            categoryRaw: "subscription",
            totalAmount: 600,
            originalCurrencyCode: "USD",
            billingTypeRaw: "monthly",
            brandIconKey: nil,
            fallbackIconName: nil,
            iconColorHex: nil,
            nextDueDate: nil,
            isActive: true,
            isShared: false,
            splitModeRaw: "equal",
            weightsByProjectId: nil,
            projectIds: [projectDoc.id],
            createdAt: Date(),
            updatedAt: Date(),
            isDeleted: false
        )
        let milestoneDoc = makeMilestoneDocument()

        service.enqueue(try PendingSyncOperation.make(entityId: projectDoc.id, kind: .project, document: projectDoc))
        service.enqueue(try PendingSyncOperation.make(entityId: txnDoc.id, kind: .transaction, document: txnDoc))
        service.enqueue(try PendingSyncOperation.make(entityId: logDoc.id, kind: .timeLog, document: logDoc))
        service.enqueue(try PendingSyncOperation.make(entityId: catDoc.id, kind: .categoryItem, document: catDoc))
        service.enqueue(try makeOp(milestoneDoc))

        try await service.syncNow()

        let collections = Set(remote.calls.map(\.collection))
        #expect(collections == Set(["projects", "transactions", "timeLogs", "categoryItems", "milestones"]))
        #expect(service.snapshotQueue().isEmpty)
        #expect(service.status == .idle)
    }

    @Test("tombstone (isDeleted = true) round-trips through the push")
    func syncNowPushesTombstone() async throws {
        let remote = MockRemoteWriter()
        let service = FirestoreSyncService(
            currentUID: { "uid-1" },
            queueURL: makeTempQueueURL(),
            remote: remote
        )
        var doc = makeMilestoneDocument()
        doc.isDeleted = true
        service.enqueue(try makeOp(doc))

        try await service.syncNow()

        #expect(remote.lastFields["isDeleted"] as? Bool == true)
        #expect(service.snapshotQueue().isEmpty)
    }
}
